### ISSUE TITLE
Simplify now URL

### ISSUE THREAD

**Issue by demoneaux** [skidding/illustrated-algorithms#13]
You can use `now alias illustrated-algorithms-xxxxzzz.now.sh illustrated-algorithms.now.sh` in order to provide a simpler and canonical URL. Note that would need to do that for each time you `now deploy`, or you can add it to your now configuration (not really sure though).

**Comment by skidding** [comment]
[Done](https://illustrated-algorithms.now.sh/). Cant believe I didn't realize this was possible. Thanks!
