### ISSUE TITLE
Binary search improvement

### ISSUE THREAD

**Issue by mhaji** [skidding/illustrated-algorithms#21]
Firstly, awesome project.

I remember reading that it's common in many implementations of binary search to calculate the midpoint as such

    mid = (low + high) / 2

which is how it's calculated [here](https://github.com/skidding/illustrated-algorithms/blob/master/algorithms/binary-search.js#L6).

The has a subtle issue (as discussed [here](https://research.googleblog.com/2006/06/extra-extra-read-all-about-it-nearly.html
)) in that it can lead to overflow if `low` and `high` are sufficiently large enough. One way to avoid this is to calculate the midpoint as such

    mid = low + ((high - low) / 2)

This is obviously not an issue in the illustration which is searching through a list of 6 animals, however it might be worth updating the implementation for general correctness. Thoughts?

**Comment by skidding** [comment]
Integrated this in a new [Footnotes](https://github.com/skidding/illustrated-algorithms#footnotes) section. Also added a [Disclaimer](https://github.com/skidding/illustrated-algorithms#disclaimer-️) to define the scope of the project better. Hope this helps. Thanks!
