### ISSUE TITLE
Fix misalignment due to browser scrollbar

### ISSUE THREAD

**Issue by RadValentin** [skidding/illustrated-algorithms#9]
![screen shot 2017-01-26 at 12 30 40](https://cloud.githubusercontent.com/assets/3300066/22328150/4e5d1938-e3c3-11e6-97e7-ca30a5d54ad2.png)

In `page.js` get the viewport size via `document.body.clientWidth` instead of `window.width` to account for scrollbars taking up visual space.

**Comment by skidding** [comment]
Nice catch! Would you like to submit a PR?

**Comment by RadValentin** [comment]
Yep, will submit one later today

**Comment by RadValentin** [comment]
It seems that my proposed fix doesn't fully address the issue, as far as I can tell there's a case where the padding + height set [here](https://github.com/skidding/illustrated-algorithms/blob/master/components/player.js#L219-L220) exceeds the total viewport height causing the scrollbar to show up after rendering thus causing the overflow to still happen.

Let me take another stab at it this weekend to see what can be done.

**Comment by skidding** [comment]
Maybe `document.body.clientWidth` still doesn't include the scrollbar width when it's computed, because content hasn't been generated at that point.

**Comment by RadValentin** [comment]
Yes, that's the issue but I haven't been able to find a clean way around it. One suggestion would be to get the [scrollbar-size](https://www.npmjs.com/package/scrollbar-size) once and just subtract it from `window.width` when calling `getWindowSize`. What do you think about such an approach?

**Comment by RadValentin** [comment]
I guess a better way would be to determine if your content can fit on the screen without needing to scroll and adjust your CSS widths accordingly before rendering.

**Comment by skidding** [comment]
> Yes, that's the issue but I haven't been able to find a clean way around it. One suggestion would be to get the scrollbar-size once and just subtract it from window.width when calling getWindowSize. What do you think about such an approach?

Um, it [mutates the DOM on init](https://github.com/olympicsoftware/scrollbar-size/blob/dd096b90dcb0b4855212c18044cb2ad029bda478/scrollbar-size.js#L16-L36) so no.

> EDIT: or if you're feeling nostalgic setting display: table-cell on each .side and display:table on their parent so that they'll try to negotiate their target widths but even if not enough horizontal space is available they'll not overflow.

Could work. I'm OK if it doesn't mess up anything else. Note that in portrait mode we do want the columns to become rows. Another option might be dropping the `float` and using position absolute. The layout system already knows if orientation is landscape or portrait, and we can add a style based on it (i.e. `left: 50%` to the code side).

**Comment by RadValentin** [comment]
Yeah, I liked the second option as well, should be doable with some clever CSS, I'll give it a go.

**Comment by dhenson02** [comment]
if it's all about the scrollbar size, just put this in the CSS:

```css
html {
    overflow-y: scroll;
}
```
